## Specify the GRB parameters

grb:

  # Location and distance (degrees and Mpc)
  ra: 10.
  dec: 10.
  distance: 500.

  # lightcurve
  K: 80. # intensity
  t_rise: 1. # rise time
  t_decay: 2.1 # decay time


# specify the detectors
# each entry is treated as the name of the detector
detectors:

  # name the detector
  det1:

    # it's location in GCRS
    ra: 10.
    dec: 0.
    altitude: 3000. # km
    time: '2010-01-01T00:00:00' # time of detection

    # Where the detector point in the sky
    pointing:
      ra: 10.
      dec: 10.

    # the total effective area
    effective_area: 1.


  # add more detectors!
  
  det2:

    ra: 170.
    dec: -10.
    altitude: 300.
    time: '2010-01-01T00:00:00'
    
    pointing:
      ra: 10.
      dec: 10.

    effective_area: 1.


    
  
    
